# Generated by Django 2.1.11 on 2021-12-15 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=45, verbose_name='事件')),
                ('event_status', models.CharField(choices=[('w', '未开始'), ('p', '处理中'), ('f', '已完成')], max_length=4, verbose_name='状态')),
                ('event_level', models.CharField(choices=[('a', '警告'), ('b', '严重'), ('c', '灾难')], max_length=4, verbose_name='级别')),
                ('event_start_time', models.DateField(verbose_name='开始时间')),
                ('event_end_time', models.DateField(verbose_name='结束时间')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('event_processer', models.ForeignKey(default='1', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='event_processer_user', to=settings.AUTH_USER_MODEL, verbose_name='处理人')),
            ],
            options={
                'verbose_name': '事件管理',
                'verbose_name_plural': '运维事件信息',
                'db_table': 'event',
                'ordering': ['-id'],
                'permissions': (('opstool_read_event', '查看事件权限'), ('opstool_add_event', '新建事件权限'), ('opstool_update_event', '更新事件权限'), ('opstool_delete_event', '删除时间权限')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='FaultRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fault_name', models.CharField(max_length=45, verbose_name='事件')),
                ('fault_status', models.BooleanField(choices=[(0, '未开始'), (1, '处理中')], max_length=4, verbose_name='状态')),
                ('fault_level', models.CharField(choices=[('a', '一级故障'), ('b', '二级故障'), ('c', '三级故障'), ('d', '四级故障'), ('e', '五级故障')], max_length=4, verbose_name='级别')),
                ('fault_report', models.FileField(blank=True, null=True, upload_to='uploads/', verbose_name='故障报告')),
                ('fault_issue', models.CharField(blank=True, max_length=200, null=True, verbose_name='故障原因')),
                ('fault_summary', models.CharField(blank=True, max_length=500, null=True, verbose_name='故障总结')),
                ('fault_start_time', models.DateField(verbose_name='开始时间')),
                ('fault_end_time', models.DateField(verbose_name='结束时间')),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('falut_person', models.ForeignKey(default='1', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='fault_person_user', to=settings.AUTH_USER_MODEL, verbose_name='责任人')),
                ('fault_processer', models.ForeignKey(default='1', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='fault_processer_user', to=settings.AUTH_USER_MODEL, verbose_name='处理人')),
            ],
            options={
                'verbose_name': '故障管理',
                'verbose_name_plural': '运维故障信息',
                'db_table': 'fault',
                'ordering': ['-id'],
                'permissions': (('opstool_read_fault', '查看故障权限'), ('opstool_add_fault', '新建故障权限'), ('opstool_update_fault', '更新故障权限'), ('opstool_delete_fault', '删除故障权限')),
                'default_permissions': (),
            },
        ),
    ]
