# Generated by Django 2.1.11 on 2021-12-15 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certs',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45, verbose_name='名称')),
                ('domain', models.CharField(max_length=128, null=True, verbose_name='通用名称')),
                ('orther_domain', models.TextField(blank=True, max_length=4096, null=True, verbose_name='备用名称')),
                ('organization_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='Organization Name')),
                ('serial_number', models.CharField(blank=True, max_length=64, null=True, verbose_name='Serial number')),
                ('issued_by', models.CharField(blank=True, max_length=64, null=True, verbose_name='Issued By')),
                ('cert_type', models.CharField(blank=True, max_length=4, null=True, verbose_name='证书类型')),
                ('method', models.BooleanField(choices=[(0, '域名'), (1, '证书')], default=0, verbose_name='Cert Detection Approach')),
                ('domain_url', models.CharField(blank=True, max_length=128, null=True, verbose_name='域名')),
                ('public_ip', models.CharField(max_length=64, verbose_name='公网地址')),
                ('real_svc', models.CharField(max_length=64, verbose_name='真实服务地址端口')),
                ('crt_file', models.TextField(blank=True, null=True, verbose_name='Crt File')),
                ('key_file', models.TextField(blank=True, null=True, verbose_name='Key File')),
                ('notbefore', models.CharField(blank=True, max_length=24, null=True, verbose_name='Not Before')),
                ('notafter', models.CharField(blank=True, max_length=24, null=True, verbose_name='Not After')),
                ('remain_days', models.IntegerField(blank=True, null=True, verbose_name='Remaining Days')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date created')),
                ('update_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Update Time')),
                ('comment', models.TextField(blank=True, max_length=128, null=True, verbose_name='Comment')),
                ('processer', models.ForeignKey(default='1', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='cert_user', to=settings.AUTH_USER_MODEL, verbose_name='责任人')),
            ],
            options={
                'verbose_name': '证书管理',
                'verbose_name_plural': '证书信息',
                'db_table': 'certs',
                'ordering': ['-id'],
                'permissions': (('cert_read', '读取证书权限'), ('cert_change', '更改证书权限'), ('account_add', '添加证书权限'), ('account_delete', '删除证书权限')),
                'default_permissions': (),
            },
        ),
    ]
